name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Move built jars
        run: |
          mkdir staging
          cp -r common/target staging/common
          cp -r target staging/configapi
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: Artifacts
          path: staging
